export const BASE_URL = import.meta.env.VITE_API_URL || "https://first-repo-production-63fe.up.railway.app";
export const USERS_URL = "/api/v1/users";
export const CATEGORY_URL = "/api/v1/category";
export const PRODUCT_URL = "/api/v1/products";
export const COUPON_URL = "/api/v1/coupon";
export const UPLOAD_URL = "/api/v1/upload";
export const ORDERS_URL = "/api/v1/orders";
export const PAYPAL_URL = "/api/v1/config/paypal"; // Adding this export to fix the crash
export const RAZORPAY_URL = "/api/v1/razorpay";
